---
title: "Ken Nyholm's website"
---

Welcome to my website!

Here you can find papers, MATLAB and Julia code related to my work on yield curve modelling, fixed income markets, and asset allocation.

### Textbook - work in progress

I am currently writing a web-based textbook called: [*A Practitioner's Guide to Financial Market Analysis*](/textbook/index.html), with the aim to include the topics covered by intermediate finance textbooks garnished with practical examples. Take a look at the current draft chapter and feel free to give me feedback!

### Links

Find me on [Google Scholar](https://scholar.google.com/citations?user=IexGlR8AAAAJ), [ResearchGate](https://www.researchgate.net/profile/Ken-Nyholm), and the [ECB author page](https://www.ecb.europa.eu/pub/research/authors/profiles/ken-nyholm.en.html).

### Disclaimer
I work at the European Central Bank. Views expressed on this site are my own and do not necessarily represent the ECB. Please read the [disclaimer](disclaimer.qmd).

